### ISSUE TITLE
interactive restore file

### ISSUE THREAD

**Issue by badwatt** [ClementNerma/Trasher#1]
Hi, it would be awesome if you implement a way to restore interactively any file inside the TRASH_DIR.
Recently I've been using [dialoguer](https://docs.rs/dialoguer/latest/dialoguer/) to achieve this in my projects and it's been amazing.

**Comment by ClementNerma** [comment]
Great suggestion! I'll look into that in the next few days.

In the meantime, you can use `trasher ls` to see all d'être files. But I agree an interactive UI would be nice.

I think I'll display a browseable list with a little fuzzy finder on top to allow searching in the files.

**Comment by ClementNerma** [comment]
Ok so I just implemented it 😆 

Truth is I was working on a fuzzy finder for the last few days, so I adapted it a little bit and integrated it into Trasher.

Now you can do `trasher unrm-ui` (or `trasher restore-with-ui`) and you'll get a nice fuzzy finder showing you all removed files with their deletion timestamps. Filter results, select one and it will be automatically restored.

The `Escape` key allows you to quit the fuzzy finder without restoring anything.

Tell me if this suits your needs :)

**Comment by badwatt** [comment]
WOW! That was fast 👍🏻 
You are awesome @ClementNerma.
Thank you so much.
