### ISSUE TITLE
No way to set a custom trashbin path, and no moving across FS support for move_pbr )':

### ISSUE THREAD

**Issue by cig0** [ClementNerma/Trasher#2]
Hi :wave: 

Life was all unicorns and rainbows with version `2.1.0` until the Black Dark arrived. Now, the realm is dying. No more rainbows. No more happy unicorns. And what's worst, Trasher being broken over here :sob: 

_Context:_ I run Fedora Atomic Desktop at home (a.k.a. "immutable" OS) on my three hosts: the desktop, the laptop, and a headless MiniPC. Because of how this flavor of Fedora works, powered by OSTree, the `/var` directory is mounted separately from the root filesystem to allow it to be writable.

_The issue:_ With version `3.1.10`, Trasher expects to create its trash bin directory in `/var/`, which doesn´t work with OSTree's directory layout. At the same time, the option to configure a custom path for the trash bin has been removed. Altogether, these two changes render version `3.1.10` unusable for me. Moreover, I expect this issue to replicate in other so-called immutable distros, like openSUSE MicroOS (I have yet to confirm that).

_Questions:_ a) Are you planning to fix the issue `not yet implemented: moving across FS with move_pbr`? b) Are there any plans to bring back the option to define a custom trash directory?

Thanks!

**Comment by ClementNerma** [comment]
I love your message ^^

I just implemented what you wanted, basically you can now add a `--exclude` flag with a list of directories. Their trash directory will point to your home directory's trash dir.

I also implemented cross-filesystem transfers. So now you can do `trasher rm /var/something --exclude /var` and it move the file to `$HOME/.trash` :)

**Comment by cig0** [comment]
@ClementNerma I confirm that with version `3.2.0`, I can use again `/var/.trasher` for the `trash-path` and also that the flag `--exclude` works as advertised.

Thanks a ton! :pray:
