### ISSUE TITLE
`trasher --exclude /var ls` throws `Permission denied (os error 13)` error

### ISSUE THREAD

**Issue by cig0** [ClementNerma/Trasher#3]
Hi again,

I'm not sure why the `ls` command started failing; please find the full context in the screenshot below:

![Spectacle-Screenshot_20240407_121301](https://github.com/ClementNerma/Trasher/assets/394089/f85da5f8-021a-4a57-832a-762d3961b1f2)`

Feel free to let me know if there's any additional feedback I can help submit to find the issue!

**Comment by ClementNerma** [comment]
So basically, Trasher lists all moutpoints in your system, and tries to canonicalize them by traversing these paths.

It seems like you do not even have read permissions on one of these mountpoints, which is not handled currently. I'll update the code so it works for you.

**Comment by cig0** [comment]
Oh, I see. Thanks for explaining how Trasher works.

**Comment by ClementNerma** [comment]
Ok so I decided to _not_ handle missing permissions. as it could create some confusions.

Instead, you'll be suggested to add the directory to your exclusion list.

I've also marked some directories to be always excluded, notably `/sys`. The complete list is:

* `/bin`
* `/boot`
* `/dev`
* `/lost+found`
* `/usr`
* `/proc`
* `/sbin`
* `/snap`
* `/sys`

This takes effect starting from version `v3.2.1`.

**Comment by cig0** [comment]
Hi Clement,

Same thing :thinking: 

![Spectacle-Screenshot_20240410_084718](https://github.com/ClementNerma/Trasher/assets/394089/8d02d011-3f80-4134-b13e-fe09c42e1813)

**Comment by ClementNerma** [comment]
Ok I think I know what's going on ; I've been excluding items after canonicalization instead of before, this should work fine on new v3.2.2. Could you try it please?

**Comment by cig0** [comment]
You nailed it! :tada: 

Now since we are here...

- The `drop` command throws back `Not a directory (os error 20)` when trying to remove a file that exists in the trash bin:

![Spectacle-Screenshot_20240410_092918](https://github.com/ClementNerma/Trasher/assets/394089/618cc4fe-2cc9-4a0e-a79b-3080aac2fe63)

Note: I also tried with `trasher --exclude /var drop --id BMKZ trasher-x86_64-unknown-linux-musl.tgz` and got the same result.

Edit: I went ahead and tried all the commands to make sure everything was working correctly.

**Comment by ClementNerma** [comment]
Ok I made new changes!

Some UI elements are now clearer, and your specific problem was solved. You can find this in v3.3.0.

It's nice to get another real user as it helps highlighting the flaws of the program and then fixing them ^^

**Comment by cig0** [comment]
I'm happy to help if anything because it is in my best interest! It's a win-win situation :muscle: Once I finally have the time to take Rust off the back burner, I'll take a deep dive into your code to learn new stuff.

**I confirm the changes you made work as intended**. When can I expect to see the update reflected in Crates.io?

As a side and fun note, after manually creating `/var/.trasher` and giving it the proper access rights, everything also works as intended, with `trasher empty` displaying an error message even as the job is done:

```bash
cig0/Downloads/trashe on  main [?] % ./trasher -V                       
trasher 3.3.0

cig0/Downloads/trashe on  main [?] % ./trasher ls
All trashes are empty.

cig0/Downloads/trashe on  main [?] % ./trasher trash-path
/var/.trasher

cig0/Downloads/trashe on  main [?] % touch aaa

cig0/Downloads/trashe on  main [?] % ./trasher rm aaa                                                           
Moving item to trash directory /var/.trasher

cig0/Downloads/trashe on  main [?] % ./trasher ls    
┌──────┬──────────┬──────┬──────┬─────────────────────────────────┬─────────────────┐
│ Type ┆ Filename ┆ Size ┆ ID   ┆ Deleted on                      ┆ Trash directory │
╞══════╪══════════╪══════╪══════╪═════════════════════════════════╪═════════════════╡
│ File ┆ aaa      ┆ 0 B  ┆ SyZx ┆ Wed, 10 Apr 2024 19:44:52 -0300 ┆ /var/.trasher   │
└──────┴──────────┴──────┴──────┴─────────────────────────────────┴─────────────────┘

cig0/Downloads/trashe on  main [?] % ./trasher empty
You are about to delete the entire trash directories of:

  /var/.trasher (1 items)

Are you sure you want to continue [Y/N]?
y
Emptying the trash...
Emptying trash directory: /var/.trasher
Failed to empty the trash at path: /var/.trasher

Permission denied (os error 13)
ERROR: Failed to empty trash directories

cig0/Downloads/trashe on  main [?] ❌1 % ./trasher ls   
All trashes are empty.
```

**Comment by ClementNerma** [comment]
Yeah that's normal, you're not supposed to create the trash directory yourself ^^

I'll close this issue, if you have other problems, please reopen it or open another issue :)
